language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -n mtoolbox -f envs/environment.yaml
  - conda activate mtoolbox
  - export PYTHONPATH="$PYTHONPATH:."
script:
  - pytest -v test/test_mt_classifier.py
